import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MovieProvider } from "@/context/movies";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-zinc-900'}>
        <MovieProvider>
          <nav>
            <ul>
              <li className="px-4"><Link href="/">Home</Link></li>
              <li className="px-4"><Link href="/movies">All the movies</Link></li>
            </ul>
          </nav>
          {children}
        </MovieProvider>
      </body>
    </html>
  );
}
